import React from 'react';
import './style.less';

export default class Footer extends React.Component {
  render() {
    return (
      <footer>
        <p>
          Created by Rayn, Generated by <a href="https://github.com/Raynxxx/FrontEndToys/tree/master/resume">
             My own resume generator
          </a>
        </p>
      </footer>
    );
  }
}

